### ISSUE TITLE
A text input problem in Android

### ISSUE THREAD

**Issue by moritayasuaki** [mideind/Velthyding#8]
When typing in Gboard on Android, an unintended string is automatically added to the "Translate from" text box in Greynir when Gboard shows user input suggestions.

**Comment by moritayasuaki** [comment]
It seems to be a front-end only problem, so I tried to solve it.
However, I realized that I needed to mock the backend in order to test it.

**Comment by vesteinn** [comment]
Thanks for the feedback, we'll look into it! Good Android support had not been available for Slate.js (the underlying editor), but I think that may have changed with some recent releases. Having said that, we should probably show some sort of notice on Android devices until the upgrade is in place.
